# Generated by Django 4.2.1 on 2023-06-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capitalname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capitalpopulation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cpopulation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('spopulation', models.IntegerField()),
                ('capitalname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.capital')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('dpopulation', models.IntegerField()),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
        migrations.AddField(
            model_name='capital',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
